### ISSUE TITLE
Allow to specify models to generate for

### ISSUE THREAD

**Issue by hovancik** [humzahkiani/rails-mermaid_erd_markdown#7]
Hi and thanks a lot for this gem 💎 

Would be great if we could tell generator to ignore specific models / specify which models to use. 

I for example use `good_job` for background jobs which has a lot of tables, but don't wanna see then in my ERD :) 

Thanks again!

**Comment by humzahkiani** [comment]
Hey, thanks for the feedback. Glad you're enjoying the gem. 

That is the next improvement I am looking to make! Might take a few weeks depending on my availability. 
You are welcome to submit a PR if you would like it earlier.

**Comment by humzahkiani** [comment]
@hovancik I had some spare time and took a stab at this. 
Mind trying it out? Let me know if you have any feedback. 

https://github.com/humzahkiani/rails-mermaid_erd_markdown/pull/8

**Comment by hovancik** [comment]
Hi, seems to work ok :) 

One thing though: it's hard to know which models let's say GoodJob has, so it might be more user friendly to specify not which models to ignore but which to use.

**Comment by humzahkiani** [comment]
I get what you're saying. I think in the typical Rails app you have more manually created models than those created through some Gem. There are also times when you want to be able to include those in the ERB as well. 

I would prefer a user starts from full transparency and move to obfuscation, than vice versa. Otherwise, they can form misapprehensions about their data. 

The flow I'm imagining is:
User generates full ERD --> User notices models they wish to ignore --> User adds models to `ignored_models` --> User generates filtered ERD

**Comment by hovancik** [comment]
yeah one way or another it is not that important :)

**Comment by humzahkiani** [comment]
Great! Just released the latest version with the feature :)
